### ISSUE TITLE
Decide on the new API namespace

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-backend-node#15]
_From @georgiana-b on October 16, 2017 6:50_

_From @nightsh on April 16, 2017 18:59_

This is a crazy small issue, I know. But a lot of things on the operations side depend on whether we replace the `v1` namespace or create a new, shiny `v2`.

I'd advocate for the latter, as we might want to keep two APIs up for a while, for a bunch of various reasons. We can discuss this below, if needed, but it's a discussion I'd rather like happening sooner than later.

_Copied from original issue: tenders-exposed/elvis-backend#39_

_Copied from original issue: tenders-exposed/elvis-backend-py#19_

**Comment by georgiana-b** [comment]
Agreed. Let's drop `api` as requested in #16 and replace `v1`  with `v2`.

**Comment by nightsh** [comment]
Ideally we'd have a variable namespace, useful for example in deployments alongside other things (e.g. the frontend, or other app, on the same domain). But since this is a very specific API project, I wouldn't expect people installing it as it were a wordpress instance. I am still more than happy to see all "introductory" namespaces such as `/api/` gone.

**Comment by georgiana-b** [comment]
The new API is up on https://api.tenders.exposed/docs/#/, no namespace because we use Swagger no there's not need to keep track of payload shema like that.
