### ISSUE TITLE
Update account password

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-backend-node#34]
Besides `GET` and `DELETE` operations on accounts, we also need to support `PATCH` in order to:

* update password (with/without password confirmation field, see #33)
* update other account related fields, if / when necessary (display name etc.)

My best guess is that the non-updateable fields are ID and email (which would complicate the scenarios too much), so they should only be accepted, but ignored in the payload (see `additionalProperties` property in [Swagger docs](https://swagger.io/docs/specification/data-models/data-types#free-form))

**Comment by georgiana-b** [comment]
To avoid having a user locked out by someone who changes his password just by having access to the user's computer, the usual implementation of this feature requires the old password along with the new password.

We allow users to make accounts via third-party login, so with no password. For such cases this feature cannot be safely provided because there is no old password to check against before making changes.

This adds complexity I don't think this functionality is worthy of, especially since users will be able to change their password via account recovery (#32) which is also safe for accounts with no previous password.

However, I do agree the other account details should be updateable so I extended the specs in #11. I'll close this for now. If this is really such a pain for the users we can always reopen it.
